defmodule Game.Words do

  @words [
    "sunset",
    "fireworks",
    "life preserver",
    "snowman",
    "christmas lights",
    "hula dance",
    "bungee jump",
    "trampoline",
    "hula hoop",
    "unicycle",
    "parachute",
    "merry-go-round",
    "canned food",
    "health supplement",
    "gum",
    "plastic bottle",
    "water bottle",
    "aluminum foil",
    "white robe",
    "X-ray",
    "thermometer",
    "bandage",
    "intravenous",
    "dumbbell",
    "alien",
    "caveman",
    "phantom",
    "robot",
    "mermaid",
    "fairy",
    "jump rope",
    "hurdle",
    "horse riding",
    "gymnastics",
    "training",
    "helmet",
    "sewing machine",
    "embroidery",
    "vacuum cleaner",
    "recipe",
    "iron",
    "dry cleaning",
    "savanna",
    "desert",
    "cliff",
    "waterfall",
    "jungle",
    "aurora",
    "chair back",
    "drawer",
    "hanger",
    "zipper",
    "key",
    "pocket",
    "lottery",
    "poster",
    "bingo",
    "rock-paper-scissors",
    "stuffed animal",
    "magic trick",
    "submarine",
    "yacht",
    "taxi",
    "helicopter",
    "hot air balloon",
    "blimp",
    "vein",
    "muscle",
    "brain",
    "belly button",
    "mole",
    "nail",
    "lip balm",
    "tattoo",
    "sunglasses",
    "hairdryer",
    "slippers",
    "pearl",
    "experiment",
    "research",
    "gold medal",
    "time machine",
    "internet",
    "radio",
    "crown",
    "diamond",
    "carbon dioxide",
    "oil",
    "meteorite",
    "shooting star",
    "diaper",
    "lullaby",
    "baby stroller",
    "pregnancy",
    "baby",
    "playing house",
    "test",
    "english",
    "studying",
    "interpreting",
    "sign language",
    "speech",
    "pajamas",
    "necktie",
    "apron",
    "swimsuit",
    "rain coat",
    "ring",
    "stroll",
    "greeting",
    "skipping",
    "fallen leaf",
    "blink",
    "day off",
    "oil painting",
    "mask",
    "sculpture",
    "crayon",
    "scribble",
    "clay",
    "Easter island statue",
    "The Sphinx",
    "The Great Wall",
    "deserted island",
    "globe",
    "adventure",
    "coloring book",
    "flower bouquet",
    "paper airplane",
    "bonfire",
    "music box",
    "fishing rod",
    "basement",
    "balcony",
    "elevator",
    "spiral staircase",
    "escalator",
    "ladder",
    "wheelchair",
    "caravan",
    "skateboard",
    "suitcase",
    "battery charger",
    "fountain",
    "mic",
    "orchestra",
    "chorus",
    "music sheet",
    "musical",
    "rythm",
    "blinds",
    "fluorescent light",
    "carpet",
    "ventilation fan",
    "electrical outlet",
    "curtain",
    "pegasus",
    "nightmare",
    "dragon",
    "anime",
    "picture book",
    "album",
    "rainbow",
    "life",
    "love",
    "lie",
    "earthquake",
    "typhoon",
    "gear",
    "screw",
    "tire",
    "engine",
    "antenna",
    "oven",
    "bookmark",
    "stamp",
    "cardboard box",
    "barcode",
    "receipt",
    "copy machine",
    "demon",
    "witch",
    "mummy",
    "hypnotism",
    "yeti",
    "Santa Claus",
    "driver's license",
    "passport",
    "ticket",
    "promise",
    "stocks",
    "tax",
    "headache",
    "breaktime",
    "massage",
    "yawn",
    "sneeze",
    "runny nose",
    "tear",
    "smile",
    "anger",
    "hard work",
    "bravery",
    "memory",
    "sleep",
    "breathing",
    "broken bone",
    "tooth decay",
    "lost item",
    "band-aid",
    "law",
    "trial",
    "election",
    "tourism",
    "foreign trade",
    "signature",
    "dinosaur",
    "wooly mammoth",
    "fossil",
    "travel guide",
    "magnifying glass",
    "cloud",
    "hide-and-seek",
    "homework",
    "fight",
    "letter",
    "friend",
    "morning",
    "horse-drawn carriage",
    "king",
    "pirate",
    "ruins",
    "myth",
    "ninja",
    "circus",
    "jack-in-the-box",
    "planetarium",
    "puppet show",
    "movie theater",
    "pool",
    "flower vase",
    "thumb tack",
    "glue",
    "soap bubble",
    "chandelier",
    "cactus",
    "railway tracks",
    "vending machine",
    "bench",
    "manhole",
    "seat belt",
    "puddle",
  ]

  def list(), do: @words
end
